### ISSUE TITLE
Try using a video for the header image

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_freeflownation#1]
For home page, can we try using this video as the header?

https://pixabay.com/videos/evening-grasses-lakeside-sunset-6514/

*Note: I'm not tied to this video, I just want to see how it looks.*

**Comment by samaradel** [comment]
[Screencast from 23-08-23 14:44:44.webm](https://github.com/ourworldventures/www_freeflownation/assets/11662805/26d239c4-db2b-4622-97ae-2eba2d8cb9e0)

**Comment by samtaggart** [comment]
It's looking good. Is there any way to make the text pure white still? And it looks like there is a semi-transparent layer over the video which is making it darker. Was this intentional?

**Comment by samtaggart** [comment]
Also take a look at how the menu disappears when you scroll down. Will send you on Telegram.

**Comment by ehab-hassan** [comment]
> It's looking good. Is there any way to make the text pure white still? And it looks like there is a semi-transparent layer over the video which is making it darker. Was this intentional?

yes, so the text can be readable but we can adjust all settings when you have the final video

**Comment by ehab-hassan** [comment]
> Also take a look at how the menu disappears when you scroll down. Will send you on Telegram.
![image](https://github.com/ourworldventures/www_freeflownation/assets/10484295/0e510799-844b-42a1-a298-c053f0716b76)

fixed

**Comment by samtaggart** [comment]
Marking as done for now! Thanks.
