### ISSUE TITLE
Buttons leading to other pages on the same website should open in the same tab

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_freeflownation#2]
Right now they are opening in a new tab, not sure why.

**Comment by ehab-hassan** [comment]
fixed

**Comment by samtaggart** [comment]
Thank you!

**Comment by samtaggart** [comment]
What was the issue by the way @ehab-hassan ? It looked like the buttons were being done the same way as other sites. Was it the "marks" ?

**Comment by ehab-hassan** [comment]
it was something related to the path name of the website that needed to be updated at custome.js
