### ISSUE TITLE
Fix the font / type on top of the animated video on the home page header

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_freeflownation#5]
Right now we have added some kind of darker gradient over the video and the text is a bit transparent. Not sure how to improve exactly but I leave it up to the team to figure it out. Thanks!

**Comment by ehab-hassan** [comment]
![image](https://github.com/ourworldventures/www_freeflownation/assets/10484295/2a41c0fb-52f6-4fb6-a98d-12bbccda06a6)
done

**Comment by samtaggart** [comment]
Niceee looks good
