### ISSUE TITLE
Set the favicon – on the website browser view

### ISSUE THREAD

**Issue by samtaggart** [ourworldventures/www_freeflownation#6]

**Comment by samtaggart** [comment]
![favicon](https://github.com/ourworldventures/www_freeflownation/assets/50134479/ce0a3673-ed0e-4a28-9156-5e13a6332b9b)

@ehab-hassan Can you help with this? Possible to remove the white BG as well?

**Comment by ehab-hassan** [comment]
done

**Comment by samtaggart** [comment]
Thanks!
